services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - WWWUSER=${UID:-1000}  # Use WSL2 user's UID
      - WWWGROUP=${GID:-1000}
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    tty: true